# -*- coding: utf-8 -*-
"""Kurs_Final_Projeleri_Entegrasyon_ve_Uygulama_(30_Proje).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jk_VRczNO4ZuUESGXkPLLyk_L4G1A78Y

## 🎓 Kurs Final Projeleri: Entegrasyon ve Uygulama (30 Proje)

### Bölüm A: Temel Entegrasyon Projeleri (OOP, Flask, ORM/API)

| # | Proje Konusu | Dosya Yapısı ve Bileşenler | Proje Yapısı (Gereksinimler) |
| :--- | :--- | :--- | :--- |
| **A1** | **OOP Tabanlı To-Do Uygulaması** | `app.py`, `models.py`, `templates/`, `static/` | **OOP:** `Gorev` sınıfı (başlık, açıklama, durum). **Flask & ORM:** `Flask-SQLAlchemy` ile görevleri kalıcı saklama (CRUD). **Web:** Görevleri listeleme ve durumunu (Tamamlandı/Beklemede) güncelleme. |
| **A2** | **Kişisel URL Kısaltıcı** | `app.py`, `models.py`, `templates/` | **ORM:** `URL` modeli (orijinal URL, kısa kod, ziyaret sayısı). **Route:** Dinamik yönlendirme (`/<kisa_kod>`). **Fonksiyon:** Benzersiz kısa kod üreten bir yardımcı fonksiyon. **İstatistik:** Her yönlendirmede `ziyaret_sayisi`'nı artırma. |
| **A3** | **Basit Hava Durumu Portalı** | `app.py`, `templates/`, `requests` | **API:** Kullanıcıdan şehir adı alan bir form. `requests` ile OpenWeatherMap (veya benzeri) API'sine bağlanma. **JSON:** Gelen veriyi çözüp (sıcaklık, açıklama) Jinja2 ile ekrana sunma. **Hata:** 404/Bağlantı hatalarını yönetme. |
| **A4** | **Dosya Yükleme ve Görüntüleme** | `app.py`, `models.py`, `templates/`, `static/uploads/` | **Veritabanı:** `Dosya` modeli (ad, yol, yükleme tarihi). **Form:** Dosya yükleme formu (`request.files`). **Güvenlik:** `secure_filename` kullanarak dosyayı güvenli kaydetme. **Web:** Yüklenen dosyaların bir listesini gösterme ve statik yoldan erişimini sağlama. |
| **A5** | **Basit Not Defteri API'si** | `app.py`, `models.py` | **ORM:** `Not` modeli (başlık, içerik). **API:** GET (`/api/notlar`) ile tüm notları JSON olarak listeleme. POST (`/api/notlar`) ile yeni not ekleme. **JSON:** `jsonify` kullanarak yanıt döndürme. |

### Bölüm B: İleri Web ve ORM Projeleri (Kalıtım, İlişkiler, Yetkilendirme)

| # | Proje Konusu | Dosya Yapısı ve Bileşenler | Proje Yapısı (Gereksinimler) |
| :--- | :--- | :--- | :--- |
| **B6** | **Çok Kullanıcılı Blog (Roller)** | `app.py`, `models.py`, `templates/`, `security/` | **Kullanıcı Yönetimi:** Kayıt/Giriş sistemi. **Rol:** Kullanıcılara `Yazar` ve `Okuyucu` rolleri atama. **Yetkilendirme:** Makale ekleme/düzenleme işlemlerini sadece `Yazar` rolüne sahip kullanıcılara kısıtlama (dekoratörler kullanın). **Veritabanı:** `Kullanici` ve `Makale` (Bire-Çok) ilişkisi. |
| **B7** | **E-Ticaret Sepeti Sistemi** | `app.py`, `models.py`, `templates/` | **Veritabanı:** `Urun` modeli. **Oturum:** Sepet içeriğini **Flask Session** içinde saklama (ürün ID ve miktar). **İşlem:** Sepete ekleme, miktarı değiştirme ve sepetten çıkarma route'ları. **Arayüz:** Sepet sayfasında toplam tutarı hesaplayarak gösterme. |
| **B8** | **Sosyal Etiketleme Sistemi** | `app.py`, `models.py`, `templates/` | **Çoktan-Çoğa:** `Gonderi` ve `Etiket` modelleri arasında Çoktan-Çoğa ilişkisi. **Fonksiyon:** Gönderi eklerken girilen etiketleri ayırıp veritabanına kaydetme. **Filtreleme:** Etikete tıklanınca sadece o etikete sahip gönderileri listeleme. |
| **B9** | **Basit Admin Paneli** | `app.py`, `models.py`, `templates/admin/` | **CRUD:** Veritabanındaki 2-3 model (Örn: `Musteri`, `Siparis`) için kullanıcı arayüzü üzerinden listeleme, ekleme, düzenleme ve silme (Admin paneli). **Geri Bildirim:** Her işlem sonrası `flask.flash` ile başarı/hata mesajı gösterme. |
| **B10** | **Dinamik Takip API'si** | `app.py`, `models.py` | **Kendi Kendine İlişki:** `Kullanici` modelinde, takipçi ve takip edilenleri tutan **kendi kendine referans veren** Çoktan-Çoğa ilişkisi. **API:** POST (`/api/takip/<id>`) ile kullanıcı takip etme ve GET (`/api/kullanici/<id>/takipciler`) ile takipçileri listeleme endpoint'leri. |

### Bölüm C: Veri Analizi ve Otomasyon Projeleri (NumPy, Pandas, API, Scraping)

| # | Proje Konusu | Dosya Yapısı ve Bileşenler | Proje Yapısı (Gereksinimler) |
| :--- | :--- | :--- | :--- |
| **C11** | **Titanic Veri Analizi Raporu** | `titanic_analiz.ipynb` (Jupyter/Colab), `titanic.csv` (Veri Seti) | **Pandas:** Veri yükleme, eksik değerleri (Age medyanı) doldurma. **Gruplama:** Cinsiyet, Sınıf ve Yaş Gruplarına göre hayatta kalma oranlarını hesaplama. **Görselleştirme:** Cinsiyete ve Sınıfa göre hayatta kalmayı gösteren Seaborn Countplot ve Pclass/Fare ilişkisini gösteren Boxplot. |
| **C12** | **Ev Fiyatı İstatistik Motoru** | `ev_fiyat_analiz.py`, `housing_data.csv` | **NumPy & Pandas:** Veri yükleme. **İstatistik:** Her sütunun ortalama, medyan ve standart sapma değerlerini hesaplama. **Filtreleme:** Belirli bir bölge koduna (NumPy Boolean Masking ile) ait evlerin fiyat ortalamasını bulma. **Görselleştirme:** Ev büyüklüğü ve fiyat arasındaki ilişkiyi gösteren Matplotlib Scatter Plot. |
| **C13** | **Haber Başlıkları Kazıyıcı (Scraper)** | `scraper.py`, `requests`, `BeautifulSoup` | **Web Scraping:** Belirli bir haber sitesinin ana sayfasından `requests` ile HTML çekme. **BS4:** Haber başlıklarını ve ilgili URL'leri (CSS Selector kullanarak) çekme. **Veri Yapısı:** Çekilen verileri bir Python sözlük listesine dönüştürme. |
| **C14** | **Veri Kalitesi Kontrol Otomasyonu** | `quality_check.py`, `veri.csv` (Simüle edilmiş) | **Pandas:** CSV yükleme. **Kontrol:** Belirli bir sütundaki (`Maaş`) aykırı değerleri (3 sigma kuralı) tespit etme. **Eksik Veri:** Her sütundaki NaN oranını hesaplama. **Raporlama:** Kontrol sonuçlarını özetleyen bir Pandas DataFrame oluşturma. |
| **C15** | **Sürekli API İzleyici** | `api_izleyici.py`, `requests`, `time` | **API:** Belirli bir borsa/döviz API'sinden (simüle edilmiş) veri çekme. **Zamanlama:** Her 5 dakikada bir veri çekme döngüsü (`time.sleep`). **Veri Saklama:** Çekilen veriyi basit bir CSV dosyasına (`log.csv`) tarih/saat damgasıyla kaydetme. |

### Bölüm D: Kompleks Entegrasyon Projeleri (Flask + Veri + Otomasyon)

| # | Proje Konusu | Dosya Yapısı ve Bileşenler | Proje Yapısı (Gereksinimler) |
| :--- | :--- | :--- | :--- |
| **D16** | **Dinamik Veri Görselleştirme Paneli** | `app.py`, `templates/`, `data.csv`, `pandas`, `seaborn` | **Flask:** Veri setinin özetini (describe, info) gösteren bir sayfa. **Görselleştirme:** Kullanıcının seçtiği iki sütun arasındaki ilişkiyi gösteren **Seaborn** grafiğini (Scatter, Boxplot) Flask sayfasına gömme. |
| **D17** | **Selenium ile Login Otomasyonu** | `app.py`, `selenium`, `webdriver` | **Otomasyon:** Belirlenen bir test sitesine (`https://the-internet.herokuapp.com/login` gibi) Selenium ile girme. **Eylem:** Kullanıcı adı ve şifre girme (`send_keys`), butona tıklama. **Raporlama:** Girişin başarılı olup olmadığını kontrol edip sonucu konsola yazdırma ve WebDriver oturumunu güvenle kapatma. |
| **D18** | **Harici Veri Entegrasyonu** | `app.py`, `models.py`, `requests` | **API Çekimi:** Harici bir API'den (örneğin kullanıcı listesi) veri çekme. **ORM:** Çekilen veriyi (örneğin sadece ad ve e-posta) veritabanındaki `HariciKullanici` modeline kaydetme. **Web:** Veritabanına kaydedilen bu kullanıcıları Flask sayfasında listeleme. |
| **D19** | **Web Kazıma Veri Modeli** | `scraper.py`, `app.py`, `models.py`, `BeautifulSoup` | **Scraping:** Belirli bir siteden (Örn: filmlerin adları, puanları) veri çekme. **ORM:** Çekilen bu verileri (`Film` modeli) veritabanına kaydetme. **Flask:** Kaydedilen filmleri puana göre sıralanmış olarak listeleme. |
| **D20** | **Eksik Veri Görselleştirme Aracı** | `app.py`, `templates/`, `data.csv`, `pandas`, `matplotlib` | **Flask:** Kullanıcıdan bir CSV dosyası yüklemesini isteme. **Pandas:** Yüklenen dosyayı okuma. **Görselleştirme:** `df.isnull().sum()` çıktısını kullanarak, her sütundaki eksik veri sayısını gösteren bir Matplotlib **çubuk grafiği** oluşturma ve bunu Flask arayüzünde gösterme. |

### Bölüm E: Uzmanlık ve Prototip Projeleri (İleri Entegrasyon)

| # | Proje Konusu | Dosya Yapısı ve Bileşenler | Proje Yapısı (Gereksinimler) |
| :--- | :--- | :--- | :--- |
| **E21** | **Flask + Scraper Otomasyonu** | `app.py`, `scraper.py`, `templates/`, `Selenium` | **Web Arayüzü:** Kullanıcının bir URL girmesini isteyen Flask formu. **Arka Plan:** Form POST edildiğinde, Selenium'u Headless modda başlatma ve o URL'deki bir elementi (örneğin başlık) çekme. **Geri Bildirim:** Çekilen sonucu Flask üzerinden kullanıcıya gösterme. |
| **E22** | **Kullanıcı Kayıt Sistemi + Hashing** | `app.py`, `models.py`, `werkzeug.security` | **Güvenlik:** Parola depolamada düz metin yerine `werkzeug.security` kullanarak parola hash'leme. **Kimlik Doğrulama:** Giriş sırasında girilen parolayı hash ile karşılaştırma. **Session:** Başarılı girişten sonra kullanıcıyı oturumda tutma. |
| **E23** | **Çoklu CSV/Excel Birleştirici** | `app.py`, `templates/`, `pandas` | **Flask:** Kullanıcının 2-3 farklı CSV dosyasını yüklemesini sağlayan form. **Pandas:** Yüklenen dosyaları okuma ve ortak bir sütuna göre birleştirme (`pd.merge`). **İndirme:** Birleştirilmiş DataFrame'i yeni bir CSV dosyası olarak kullanıcıya indirme linki sunma. |
| **E24** | **Envanter Yönetimi (Çoklu İlişki)** | `app.py`, `models.py` | **İlişkiler:** `Urun`, `Depo` ve bu ikisi arasında **stok miktarını** tutan bir `DepoStok` ilişkisel modeli. **CRUD:** Depo ve Ürünler için CRUD. **Sorgulama:** Bir ürünün hangi depolarda ne kadar stok kaldığını gösteren liste oluşturma. |
| **E25** | **Matris İşlemleri Eğitimi (NumPy)** | `app.py`, `templates/`, `numpy` | **Flask:** Kullanıcının 2x2 matrisin elemanlarını girmesini sağlayan formlar. **NumPy:** Girilen matrisler üzerinde matris çarpımı, transpoze ve tersini (inverse) hesaplama. **Geri Bildirim:** Sonuç matrisini Flask sayfasında tablo formatında gösterme. |
| **E26** | **Dinamik Fiyat Takibi Simülasyonu** | `app.py`, `models.py`, `requests` | **Model:** `Urun` ve `FiyatGecmisi` (Bire-Çok). **Simülasyon:** Harici bir API'den (veya rastgele) fiyat çekme ve `FiyatGecmisi` modeline tarih/saat damgasıyla kaydetme. **Görselleştirme:** Bir ürünün fiyat geçmişini gösteren basit bir Matplotlib çizgi grafiği çizip Flask'ta gösterme. |
| **E27** | **Log Yöneticisi** | `app.py`, `models.py`, `logging` | **Model:** `LogKaydi` (Zaman, Seviye, Mesaj). **Entegrasyon:** Flask uygulamasında her route çağrıldığında bir log kaydı oluşturma ve bunu veritabanına kaydetme. **Web:** Veritabanındaki log kayıtlarını seviyeye (Hata, Bilgi) göre filtreleyerek bir sayfada listeleme. |
| **E28** | **Çerez Tabanlı Tema Seçimi** | `app.py`, `templates/` | **Arayüz:** Kullanıcıya "Açık" ve "Koyu" tema seçeneği sunma. **Çerez:** Kullanıcının seçtiği tema bilgisini bir **kalıcı çerezde** saklama. **Jinja2:** Şablonda, çerezdeki değere göre CSS sınıfını dinamik olarak değiştirerek tema uygulama. |
| **E29** | **Yorum Moderasyon Sistemi** | `app.py`, `models.py` | **Model:** `Yorum` (İçerik, Onay Durumu: True/False). **Kullanıcı:** Kullanıcıların yorum eklemesine izin verme. **Admin:** Yorumlar varsayılan olarak Onaysız başlar. Admin panelinde yorumları listeleme ve "Onayla" veya "Reddet" butonu ile durumlarını güncelleme. |
| **E30** | **Pandas Veri Özeti API'si** | `app.py`, `pandas` | **Veri:** Sabit bir CSV dosyasını (`veri.csv`) Pandas'a yükleme. **API:** GET `/api/ozet` endpoint'ine gelen istekte, tüm DataFrame'in `.describe()` çıktısını JSON formatına dönüştürüp döndürme. **API:** GET `/api/ozet/<sutun_adi>` ile sadece belirli bir sütunun istatistiklerini döndürme. |

## 🎓 Kurs Final Projeleri: Entegrasyon ve Uygulama (30 Proje)

### Bölüm A: Temel Entegrasyon Projeleri (OOP, Flask, ORM/API)

#### A1: OOP Tabanlı To-Do Uygulaması
* **Konu:** Temel CRUD işlemleri ve OOP sınıf entegrasyonu.
* **Bileşenler:** Flask, Flask-SQLAlchemy, OOP (Gorev Sınıfı).
* **Gereksinimler:**
    * `Gorev` adında bir Python sınıfı tanımlama (başlık, açıklama, durum).
    * `Flask-SQLAlchemy` ile görevleri kalıcı saklama.
    * Web arayüzü üzerinden görevleri ekleme, listeleme ve durumunu (Tamamlandı/Beklemede) güncelleme.

#### A2: Kişisel URL Kısaltıcı
* **Konu:** Veritabanı destekli yönlendirme ve basit istatistik.
* **Bileşenler:** Flask, Flask-SQLAlchemy, `random` modülü.
* **Gereksinimler:**
    * `URL` modeli (orijinal URL, kısa kod, ziyaret sayısı) tanımlama.
    * Kullanıcıdan alınan URL için benzersiz kısa kod üretme.
    * Dinamik bir route (`/<kisa_kod>`) tanımlayıp `redirect()` ile yönlendirme.
    * Her yönlendirmede ilgili kaydın ziyaret sayısını artırma.

#### A3: Basit Hava Durumu Portalı
* **Konu:** Harici API kullanımı ve JSON işleme.
* **Bileşenler:** Flask, `requests` kütüphanesi, OpenWeatherMap API (veya simülasyonu).
* **Gereksinimler:**
    * Kullanıcıdan şehir adı alan bir web formu.
    * `requests` ile harici hava durumu API'sine GET isteği yapma.
    * Gelen JSON verisini çözüp (sıcaklık, açıklama) Jinja2 ile ekrana sunma.
    * API'den dönen 404 (şehir bulunamadı) hatalarını yönetme.

#### A4: Dosya Yükleme ve Görüntüleme
* **Konu:** Medya yönetimi, form işlemleri ve güvenlik.
* **Bileşenler:** Flask, Flask-SQLAlchemy, `werkzeug.utils.secure_filename`.
* **Gereksinimler:**
    * `Dosya` modeli (ad, yol, yükleme tarihi) tanımlama.
    * Dosya yükleme formu ve `request.files` ile dosyayı alma.
    * `secure_filename` kullanarak dosyayı `static/uploads/` klasörüne güvenli kaydetme.
    * Yüklenen dosyaların bir listesini gösterme ve statik URL ile erişimini sağlama.

#### A5: Basit Not Defteri API'si
* **Konu:** JSON yanıtları ve RESTful CRUD mantığı.
* **Bileşenler:** Flask, Flask-SQLAlchemy, `jsonify`.
* **Gereksinimler:**
    * `Not` modeli (başlık, içerik) tanımlama.
    * GET `/api/notlar` ile tüm notları JSON olarak listeleme (`jsonify` kullanın).
    * POST `/api/notlar` ile `request.get_json()` kullanarak yeni not ekleme.
    * GET `/api/notlar/<int:id>` ile tek bir notu JSON olarak döndürme (Bulunamazsa 404 döndürün).

---

### Bölüm B: İleri Web ve ORM Projeleri (Kalıtım, İlişkiler, Yetkilendirme)

#### B6: Çok Kullanıcılı Blog (Roller)
* **Konu:** Kullanıcı kimlik doğrulama, yetkilendirme ve Bire-Çok ilişkisi.
* **Bileşenler:** Flask, Flask-SQLAlchemy, Parola Hashing (werkzeug).
* **Gereksinimler:**
    * `Kullanici` ve `Makale` (Bire-Çok) ilişkisi.
    * Kullanıcılara `Yazar` ve `Okuyucu` rolleri atama.
    * Makale ekleme/düzenleme işlemlerini sadece `Yazar` rolüne sahip kullanıcılara kısıtlama (Özel bir dekoratör oluşturun).
    * Giriş/Kayıt sistemi ve session yönetimi.

#### B7: E-Ticaret Sepeti Sistemi
* **Konu:** Oturum yönetimi ve dinamik hesaplama.
* **Bileşenler:** Flask, Flask-SQLAlchemy, Flask Session.
* **Gereksinimler:**
    * `Urun` modelini tanımlama.
    * Sepet içeriğini **Flask Session** içinde bir sözlük olarak saklama (ürün ID ve miktar).
    * Sepete ekleme, miktarı değiştirme ve çıkarma route'ları.
    * Sepet sayfasında `session` içeriğini listeleme ve anlık toplam tutarı hesaplayıp gösterme.

#### B8: Sosyal Etiketleme Sistemi
* **Konu:** Çoktan-Çoğa ilişkisi ve dinamik filtreleme.
* **Bileşenler:** Flask, Flask-SQLAlchemy (secondary tablo veya ilişki sınıfı).
* **Gereksinimler:**
    * `Gonderi` ve `Etiket` modelleri arasında **Çoktan-Çoğa** ilişkisi kurma.
    * Gönderi eklerken girilen etiketleri ayırıp (virgül vb.) veritabanına kaydetme.
    * Etikete tıklandığında sadece o etikete sahip gönderileri gösteren dinamik bir filtreleme sayfası oluşturma.

#### B9: Basit Admin Paneli
* **Konu:** Veritabanı modelleri için CRUD arayüzü.
* **Bileşenler:** Flask, Flask-SQLAlchemy, `flask.flash`.
* **Gereksinimler:**
    * Basit bir admin giriş sistemi.
    * İki farklı model (Örn: `Musteri`, `Siparis`) için Yönetim Sayfaları (Listeleme, Ekleme, Düzenleme).
    * Her CRUD işlemi (başarılı/hatalı) sonrası kullanıcıya `flask.flash` ile geri bildirim mesajı gösterme.

#### B10: Dinamik Takip API'si
* **Konu:** Kendi kendine referans veren Çoktan-Çoğa ilişkisi ve API.
* **Bileşenler:** Flask, Flask-SQLAlchemy, `jsonify`.
* **Gereksinimler:**
    * `Kullanici` modelini ve Takipçi/Takip Edilenleri tutan **kendi kendine referans veren** ilişkiyi tanımlama.
    * POST `/api/takip/<id>` ile kullanıcı takip etme işlemi.
    * GET `/api/kullanici/<id>/takip_ettikleri` ile bir kullanıcının takip ettiklerini JSON olarak döndürme.

---

### Bölüm C: Veri Analizi ve Otomasyon Projeleri (NumPy, Pandas, API, Scraping)

#### C11: Titanic Veri Analizi Raporu
* **Konu:** Pandas ile veri manipülasyonu ve Seaborn görselleştirme.
* **Bileşenler:** Pandas, NumPy, Seaborn, Matplotlib, `titanic.csv` (Veri Seti).
* **Gereksinimler:**
    * Veri yükleme, eksik `Age` değerlerini medyan ile doldurma.
    * Cinsiyet ve Sınıf'a göre hayatta kalma oranlarını hesaplama (`groupby`).
    * Cinsiyete göre hayatta kalmayı gösteren **Seaborn Countplot** çizme.
    * Pclass ve Fare ilişkisini gösteren **Seaborn Boxplot** çizme.

#### C12: Ev Fiyatı İstatistik Motoru
* **Konu:** İstatistiksel hesaplamalar ve NumPy/Pandas filtreleme.
* **Bileşenler:** Pandas, NumPy, Ev Fiyat Verisi (CSV).
* **Gereksinimler:**
    * Tüm sayısal sütunların ortalama, medyan ve standart sapma değerlerini hesaplama.
    * Belirli bir bölge koduna ait kayıtları filtreleme (NumPy maskesi veya Pandas `loc` kullanın).
    * Seçilen bölgedeki ev fiyatlarının ortalamasını bulma.
    * İki değişken arasındaki ilişkiyi gösteren **Matplotlib Scatter Plot** çizme.

#### C13: Haber Başlıkları Kazıyıcı (Scraper)
* **Konu:** Statik Web Scraping ve veri çıkarma.
* **Bileşenler:** `requests`, `BeautifulSoup`.
* **Gereksinimler:**
    * Belirlenen bir haber sitesinin ana sayfasından `requests` ile HTML çekme.
    * `BeautifulSoup` kullanarak haber başlıklarını ve ilgili URL'leri **CSS Seçiciler** ile çekme.
    * Çekilen verileri, her biri bir sözlük olan Python listesine dönüştürme.

#### C14: Veri Kalitesi Kontrol Otomasyonu
* **Konu:** Pandas ile veri temizliği ve raporlama.
* **Bileşenler:** Pandas, NumPy.
* **Gereksinimler:**
    * CSV yükleme ve her sütundaki `NaN` oranını hesaplama.
    * Belirli bir sayısal sütundaki **aykırı değerleri** (3 standart sapma kuralı gibi) tespit etme.
    * Tüm kontrol sonuçlarını özetleyen yeni bir Pandas DataFrame oluşturma.

#### C15: Sürekli API İzleyici
* **Konu:** Zaman tabanlı otomasyon ve API loglama.
* **Bileşenler:** `requests`, `time`, `csv` (veya Pandas).
* **Gereksinimler:**
    * Harici bir API'den (örneğin borsa verisi simülasyonu) veri çekme.
    * `time.sleep` kullanarak her 5 dakikada bir veri çeken bir döngü oluşturma.
    * Çekilen veriyi, tarih/saat damgasıyla birlikte basit bir CSV dosyasına (`log.csv`) sürekli olarak ekleme (append).

---

### Bölüm D: Kompleks Entegrasyon Projeleri (Flask + Veri + Otomasyon)

#### D16: Dinamik Veri Görselleştirme Paneli
* **Konu:** Flask'ta veri analizi ve grafik sunumu.
* **Bileşenler:** Flask, Pandas, Seaborn, Matplotlib.
* **Gereksinimler:**
    * CSV veri setini Pandas ile yükleme.
    * Kullanıcının seçtiği iki sütunu Flask formu ile alma.
    * Seçilen bu iki sütun arasındaki ilişkiyi gösteren bir **Seaborn grafiği** (örneğin Scatter Plot) oluşturma.
    * Oluşturulan grafiği Flask şablonunda görsel olarak sunma.

#### D17: Selenium ile Login Otomasyonu
* **Konu:** Tarayıcı otomasyonu (Headless, eylem zincirleme).
* **Bileşenler:** Flask, Selenium, WebDriver.
* **Gereksinimler:**
    * Flask üzerinden bir form ile hedef URL ve kimlik bilgilerini alma.
    * Form gönderildiğinde, Selenium'u **Headless** modda başlatma.
    * `find_element` ile kullanıcı adı/şifre alanlarını bulma ve `send_keys` ile veri gönderme.
    * Girişin başarılı olup olmadığını kontrol edip (örn: yeni bir elementin varlığı) sonucu Flask üzerinden geri bildirme.

#### D18: Harici Veri Entegrasyonu
* **Konu:** API'den çekilen veriyi ORM modeline kaydetme.
* **Bileşenler:** Flask, Flask-SQLAlchemy, `requests`.
* **Gereksinimler:**
    * Harici bir API'den (örneğin JSONPlaceholder kullanıcıları) veri çekme.
    * `HariciKullanici` modelini (örneğin sadece ad ve e-posta) tanımlama.
    * Çekilen veriyi döngü içinde veritabanına kaydetme.
    * Kaydedilen kullanıcıları Flask sayfasında listeleme.

#### D19: Web Kazıma Veri Modeli
* **Konu:** Scraping, ORM ve web listeleme entegrasyonu.
* **Bileşenler:** Flask, Flask-SQLAlchemy, `requests`, `BeautifulSoup`.
* **Gereksinimler:**
    * `Film` modeli (ad, puan) tanımlama.
    * Harici bir film listeleme sitesinden veri çekme.
    * Çekilen verileri `Film` modeline kaydetme.
    * Flask arayüzünde filmleri puana göre sıralanmış olarak listeleme.

#### D20: Eksik Veri Görselleştirme Aracı
* **Konu:** Dosya yükleme, Pandas analiz ve dinamik görselleştirme.
* **Bileşenler:** Flask, Pandas, Matplotlib, Dosya Yükleme.
* **Gereksinimler**
    * Kullanıcıdan bir CSV dosyası yüklemesini sağlayan Flask formu.
    * Pandas ile yüklenen dosyayı okuma.
    * `df.isnull().sum()` çıktısını kullanarak, her sütundaki eksik veri sayısını gösteren bir Matplotlib **çubuk grafiği** oluşturma.
    * Bu grafiği Flask arayüzünde dinamik olarak sunma.

---

### Bölüm E: Uzmanlık ve Prototip Projeleri (İleri Entegrasyon)

#### E21: Flask + Scraper Otomasyonu
* **Konu:** Arayüz ile arka plan otomasyonunu birleştirme.
* **Bileşenler:** Flask, Selenium (Headless), WebDriver.
* **Gereksinimler:**
    * Kullanıcının bir URL girmesini isteyen Flask formu.
    * Form POST edildiğinde, Selenium'u Headless modda başlatma.
    * Gelen URL'deki belirli bir elementi (örneğin `<h1>` etiketi) Selenium ile çekme.
    * Çekilen sonucu Flask üzerinden kullanıcıya geri bildirme.

#### E22: Kullanıcı Kayıt Sistemi + Hashing
* **Konu:** Güvenli parola yönetimi.
* **Bileşenler:** Flask, Flask-SQLAlchemy, `werkzeug.security`.
* **Gereksinimler:**
    * Kullanıcı parolasını kaydetmeden önce `werkzeug.security` ile hash'leme.
    * Giriş sırasında girilen parolayı, veritabanındaki hash ile karşılaştırma.
    * Başarılı/başarısız giriş sonrası `session` ve `flash` kullanımı.

#### E23: Çoklu CSV/Excel Birleştirici
* **Konu:** Pandas ile veri setlerini birleştirme.
* **Bileşenler:** Flask, Pandas, Dosya Yükleme.
* **Gereksinimler:**
    * Kullanıcının 2-3 farklı CSV dosyası yüklemesini sağlayan form.
    * Pandas ile dosyaları okuma.
    * Ortak bir sütuna göre dosyaları birleştirme (`pd.merge`).
    * Birleştirilmiş DataFrame'i yeni bir CSV dosyası olarak kullanıcıya indirme linki sunma.

#### E24: Envanter Yönetimi (Çoklu İlişki)
* **Konu:** İlişkisel modelleme (Ara tablo ile Çoktan-Çoğa).
* **Bileşenler:** Flask, Flask-SQLAlchemy.
* **Gereksinimler:**
    * `Urun`, `Depo` ve bu ikisi arasında **stok miktarını** tutan bir `DepoStok` ilişkisel modeli.
    * Tüm modeller için temel CRUD.
    * Bir ürünün hangi depolarda ne kadar stoku olduğunu gösteren bir sorgu (join) sayfası oluşturma.

#### E25: Matris İşlemleri Eğitimi (NumPy)
* **Konu:** Flask arayüzünden NumPy fonksiyonlarını kullanma.
* **Bileşenler:** Flask, NumPy.
* **Gereksinimler:**
    * Kullanıcının 2x2 matrisin elemanlarını girmesini sağlayan formlar.
    * NumPy ile girilen matrisler üzerinde matris çarpımı ve transpozesini hesaplama.
    * Sonuç matrisini Flask sayfasında tablo formatında gösterme.

#### E26: Dinamik Fiyat Takibi Simülasyonu
* **Konu:** Zaman serisi verilerini modelleme ve görselleştirme.
* **Bileşenler:** Flask, Flask-SQLAlchemy, Matplotlib.
* **Gereksinimler:**
    * `Urun` ve `FiyatGecmisi` (Bire-Çok) modelleri.
    * Bir ürünün fiyat geçmişini `FiyatGecmisi` modeline kaydetme (simüle edilmiş fiyatlarla).
    * Bir ürünün fiyat geçmişini gösteren basit bir Matplotlib çizgi grafiği çizip Flask'ta dinamik olarak sunma.

#### E27: Log Yöneticisi
* **Konu:** Flask ile loglama entegrasyonu ve veritabanı.
* **Bileşenler:** Flask, Flask-SQLAlchemy, Python `logging` modülü.
* **Gereksinimler:**
    * `LogKaydi` (Zaman, Seviye, Mesaj) modeli.
    * Flask uygulamasında her route çağrıldığında bir log kaydı oluşturma ve veritabanına kaydetme.
    * Log kayıtlarını seviyeye (Hata, Bilgi) göre filtreleyerek bir sayfada listeleme.

#### E28: Çerez Tabanlı Tema Seçimi
* **Konu:** Çerez yönetimi ve Jinja2'de dinamik içerik.
* **Bileşenler:** Flask (request/make_response), Çerezler.
* **Gereksinimler:**
    * Kullanıcıya "Açık" ve "Koyu" tema seçeneği sunma.
    * Seçilen tema bilgisini bir **kalıcı çerezde** saklama.
    * Jinja2 şablonunda, çerezdeki değere göre CSS sınıfını dinamik olarak değiştirerek tema uygulama.

#### E29: Yorum Moderasyon Sistemi
* **Konu:** Durum yönetimi ve yetkilendirilmiş güncelleme.
* **Bileşenler:** Flask, Flask-SQLAlchemy.
* **Gereksinimler:**
    * `Yorum` modeli (İçerik, Onay Durumu: True/False).
    * Yorumların varsayılan olarak Onaysız başlaması.
    * Admin panelinde yorumları listeleme ve "Onayla" veya "Reddet" butonu ile durumlarını güncelleme.

#### E30: Pandas Veri Özeti API'si
* **Konu:** Pandas'ın keşifçi yeteneklerini API üzerinden sunma.
* **Bileşenler:** Flask, Pandas, `jsonify`, CSV Dosyası.
* **Gereksinimler:**
    * Sabit bir CSV dosyasını Pandas'a yükleme.
    * GET `/api/ozet` endpoint'ine gelen istekte, tüm DataFrame'in `.describe()` çıktısını JSON formatına dönüştürüp döndürme.
    * GET `/api/ozet/<sutun_adi>` ile sadece belirli bir sütunun istatistiklerini JSON olarak döndürme.
"""

