# -*- coding: utf-8 -*-
"""hafta08_oturum3_veri_gorsellestirme_orjinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vbDra9kovhe43IZrkfRl-YURnlNbJE8P

#**Matplotlib Nedir?**

**Matplotlib,** Python'da 2D ve 3D grafikler oluşturmak için kullanılan kapsamlı bir görselleştirme kütüphanesidir. John Hunter tarafından 2003 yılında geliştirilmiştir ve bugün Python ekosisteminde en yaygın kullanılan görselleştirme aracıdır.


**Temel Özellikleri**  

*  MATLAB benzeri arayüz

* Yüksek kaliteli grafik üretimi

* Çok sayıda grafik türü desteği

* Geniş özelleştirme seçenekleri

* LaTeX desteği

* Etkileşimli grafikler oluşturma

**Neden Kullanılır ?**  

* Avantajları:
    1. Kolay Öğrenme: MATLAB benzeri syntax

    2. Esneklik: Her türlü grafiği özelleştirebilme

    3. Geniş Kullanım: Bilimsel araştırmalardan endüstriyel uygulamalara

    3. Entegrasyon: NumPy, Pandas gibi kütüphanelerle uyumlu

    4. Çoklu Platform: Windows, Linux, macOS'ta çalışır

* Kullanım Alanları:

    1. Veri analizi ve görselleştirme

    2. Bilimsel araştırmalar

    3. Makine öğrenmesi sonuçlarının görselleştirilmesi

    4. Finansal veri analizi

    5. Akademik yayınlar

# Temel Kurulum ve Import


```
# Kurulum
# pip install matplotlib

# Import işlemleri
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Jupyter notebook'ta grafikleri görmek için
%matplotlib inline
```
"""

# Commented out IPython magic to ensure Python compatibility.
# Kurulum
# pip install matplotlib

# Import işlemleri
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Jupyter notebook'ta grafikleri görmek için
# %matplotlib inline

"""# Temel Grafik Türleri

**Line Plot - Çizgi Grafiği**
"""

# Basit çizgi grafiği
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

plt.figure(figsize=(8, 6))
plt.plot(x, y, marker='o', linestyle='-', color='blue', linewidth=2, markersize=8)
plt.title('Basit Çizgi Grafiği', fontsize=14)
plt.xlabel('X Ekseni', fontsize=12)
plt.ylabel('Y Ekseni', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

"""#Figure ve Axes Kavramları (OOP Yaklaşımı)

Matplotlib'in en önemli felsefesi Figure (Şekil) ve Axes (Eksenler) olmak üzere iki ana bileşene dayanır. Bu, Nesne Yönelimli Programlama (OOP) yaklaşımıdır ve grafik üzerinde tam kontrol sağlar.

| Kavram  | Tanım  | Analoji  |
|---------|--------|----------|
| **Figure** | Grafiklerin çizileceği genel pencere veya tuval. Birçok Axes (eksen) içerebilir. | Bir resim çerçevesi veya beyaz bir kağıt. |
| **Axes** | Grafiğin gerçekten çizildiği alan. Verinin X ve Y eksenlerinin tanımlandığı yerdir. Her Figure birden çok Axes içerebilir. | Çerçevenin içindeki asıl resim alanı. |

"""

# 1. Figure ve Axes (eksenler) oluşturulur
# fig: Figure nesnesi (tuval)
# ax: Axes nesnesi (grafiğin çizileceği alan)
fig, ax = plt.subplots()

# 2. Veri Hazırlığı
x_verisi = [1, 2, 3, 4]
y_verisi = [10, 20, 35, 25]

# 3. Grafiği Çizme
# ax.plot() metodu ile Axes nesnesinin üzerine çizim yapılır
ax.plot(x_verisi, y_verisi)

# 4. Grafiği Gösterme (Bu komut pencereyi açar veya çıktıyı gösterir)
plt.show()

"""#İlk Çizgi Grafiği (plt.plot()) Oluşturma

plt.plot() ile en temel çizgi grafiğini çizelim ve temel ayarları yapalım. Bu kısımda, basitlik adına Procedural (prosedürel) yaklaşımı da gösterilebilir (tek bir satırda grafik çizimi).
"""

#basit çizgi grafiği - prosedürel yöntem

import matplotlib.pyplot as plt
import numpy as np

# Veri setini oluşturalım (örneğin sinüs eğrisi)
x = np.linspace(0, 10, 100) # 0'dan 10'a kadar 100 eşit aralıklı nokta
y = np.sin(x)

# Tek satırda çizim (Matlab/plt.plot() stilinde)
# Arka planda Matplotlib otomatik olarak bir Figure ve bir Axes oluşturur.
plt.plot(x, y)
plt.show()

#Çizgi Özelleştirme
# OOP Yaklaşımına geri dönelim
fig, ax = plt.subplots(figsize=(8, 4)) # figsize ile grafiğin boyutunu belirleme

# Çizgiyi özelleştirme
# 'r--' -> Kırmızı (red), kesikli çizgi (dashed line)
# linewidth -> Çizgi kalınlığı
# label -> Açıklama (legend) için etiket
ax.plot(x, y,
        'r--',
        linewidth=2,
        label='Sinüs Eğrisi')

# İkinci bir çizgi ekleyelim (Kosinüs)
ax.plot(x, np.cos(x),
        'b-',
        linewidth=1,
        label='Kosinüs Eğrisi') # 'b-' -> Mavi (blue), düz çizgi

plt.show()

"""# Grafiği Özelleştirme ve Etiketleme

Grafiğin okunabilirliğini artırmak için başlık, eksen isimleri ve gösterge (legend) eklenmesi.
"""

# detaylı etiketleme örneği
import matplotlib.pyplot as plt
import numpy as np

# Veri
x = np.linspace(0, 10, 100)
y = np.sin(x)

# Figure ve Axes oluşturma
fig, ax = plt.subplots(figsize=(10, 5)) #figsize 10*5 inc

# Çizimi yapma
ax.plot(x, y, color='purple', linestyle='-', label='Sinüs Grafiği')

# 1. Başlık Ekleme
# fontsize ile yazı boyutunu ayarlayabiliriz
ax.set_title('Zamana Bağlı Sinüs Fonksiyonu', fontsize=16, color='darkblue')

# 2. Eksen İsimleri Ekleme
ax.set_xlabel('Zaman (t)', fontsize=12)
ax.set_ylabel('Genlik (A)', fontsize=12)

# 3. Gösterge (Legend) Ekleme (label parametresi ile tanımlanan etiketleri gösterir)
ax.legend(loc='lower left') # loc: göstergenin konumu

# 4. Eksen Limitlerini Ayarlama
# Grafik üzerinde gösterilecek min/max değerleri belirler
ax.set_xlim(0, 10)
ax.set_ylim(-1.5, 1.5)

# 5. Kılavuz Çizgileri (Grid) Ekleme
ax.grid(True, linestyle=':', alpha=0.6)

plt.show()

"""#Grafiği Kaydetme
Oluşturulan grafiği bir dosyaya kaydetmek, özellikle sunumlar ve raporlar için kritiktir.
"""

# fig (Figure) nesnesi kullanılarak yapılır
fig.savefig('sinus_grafik_detayli.png',
            dpi=300,        # Yüksek çözünürlük (dots per inch)
            bbox_inches='tight') # Grafiğin etrafındaki gereksiz boşluğu kaldırır

"""#Scatter Plat ( Dağılım Grafiği)"""

#İki sürekli değişken arasındaki ilişkiyi veya korelasyonu görmek.
#ax.scatter(x,y)
import matplotlib.pyplot as plt
import numpy as np

# Rastgele veri üretelim
np.random.seed(42) # Tekrarlanabilirlik için
boy = np.random.normal(170, 10, 50) # Ortalama 170, Standart Sapma 10
kilo = boy * 0.6 + np.random.normal(5, 5, 50) # Boy ile korelasyonlu kilo

fig, ax = plt.subplots(figsize=(8, 5))

# Scatter plot çizimi
# s: nokta boyutu, c: nokta rengi, alpha: saydamlık
ax.scatter(boy, kilo,
           s=50,
           c='darkgreen',
           alpha=0.7)

ax.set_title('Boy ve Kilo İlişkisi (Scatter Plot)')
ax.set_xlabel('Boy (cm)')
ax.set_ylabel('Kilo (kg)')
ax.grid(True, linestyle='--')

plt.show()

# Dağılım grafiği
np.random.seed(42)
x = np.random.randn(100)
y = np.random.randn(100)
colors = np.random.rand(100)
sizes = 1000 * np.random.rand(100)

plt.figure(figsize=(10, 8), dpi=100)  #10*100 x 8*100 piksel
plt.scatter(x, y, c=colors, s=sizes, alpha=0.7, cmap='viridis')
plt.colorbar(label='Renk Değeri')
plt.title('Dağılım Grafiği', fontsize=14)
plt.xlabel('X Değerleri')
plt.ylabel('Y Değerleri')
plt.show()

"""#Bar Plt - Çubuk Grafik"""

#Kategorik verileri karşılaştırmak. X ekseninde kategoriler, Y ekseninde ise bu kategorilere ait değerler (sayım, ortalama vb.) bulunur.

#Komut: ax.bar(kategoriler, değerler)

# Kategorik veri
urunler = ['A', 'B', 'C', 'D', 'E']
satislar = [250, 400, 150, 350, 500]

fig, ax = plt.subplots(figsize=(8, 5))

# Bar plot çizimi
ax.bar(urunler, satislar,
       color=['skyblue', 'salmon', 'lightgreen', 'gold', 'grey'])

ax.set_title('Aylık Ürün Satışları (Bar Chart)')
ax.set_xlabel('Ürün Kategorisi')
ax.set_ylabel('Toplam Satış Adedi')

plt.show()

# Dikey çubuk grafik
kategoriler = ['A', 'B', 'C', 'D', 'E']
degerler = [23, 45, 56, 78, 33]

plt.figure(figsize=(10, 6))
bars = plt.bar(kategoriler, degerler, color=['red', 'blue', 'green', 'orange', 'purple'])
plt.title('Dikey Çubuk Grafik', fontsize=14)
plt.xlabel('Kategoriler')
plt.ylabel('Değerler')

# Çubukların üzerine değerleri yazma
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{height}', ha='center', va='bottom')

plt.show()

import matplotlib.pyplot as plt
# yatay çubuk grafik
# Veriler
kategoriler = ['A', 'B', 'C', 'D', 'E']
degerler = [23, 45, 56, 78, 33]

# Grafik boyutu
plt.figure(figsize=(10, 6))

# Yatay çubuk grafik
bars = plt.barh(kategoriler, degerler, color=['red', 'blue', 'green', 'orange', 'purple'])

# Başlık ve etiketler
plt.title('Yatay Çubuk Grafik', fontsize=14)
plt.xlabel('Değerler')
plt.ylabel('Kategoriler')

# Çubukların sonuna değerleri yazma
for bar in bars:
    width = bar.get_width()  # çubuğun uzunluğu (değeri)
    plt.text(width + 1,       # metni çubuğun hemen sağına koy
             bar.get_y() + bar.get_height()/2,  # dikeyde ortala
             f'{width}', va='center')

plt.show()

"""#histogram grafik"""

#Amaç: Bir sürekli değişkenin dağılımını (frekansını) göstermek. Veri aralıklar halinde gruplanır (bins) ve her aralıktaki gözlem sayısı çubuklarla gösterilir.

#Komut: ax.hist(veri, bins=...)

# Rastgele normal dağılımlı veri
veri = np.random.normal(loc=50, scale=10, size=1000) # Ortalama 50, Sapma 10

fig, ax = plt.subplots(figsize=(8, 5))

# Histogram çizimi
# bins: Kaç adet aralık (çubuk) kullanılacağını belirtir
ax.hist(veri,
        bins=20,
        color='teal',
        edgecolor='black', # Çubuk kenarlık rengi
        alpha=0.8)

ax.set_title('Sınav Notları Dağılımı (Histogram)')
ax.set_xlabel('Not Aralığı')
ax.set_ylabel('Frekans (Öğrenci Sayısı)')

plt.show()

# Histogram
np.random.seed(42)
data = np.random.normal(0, 1, 1000)

plt.figure(figsize=(10, 6))
plt.hist(data, bins=30, alpha=0.7, color='skyblue', edgecolor='black')
plt.title('Histogram', fontsize=14)
plt.xlabel('Değerler')
plt.ylabel('Frekans')
plt.grid(True, alpha=0.3)
plt.show()

"""#Pie Chart - Pasta Grafiği"""

# Pasta grafiği
etiketler = ['Python', 'Java', 'C++', 'JavaScript', 'Diğer']
yuzdeler = [35, 25, 20, 15, 5]
renkler = ['#ff9999', '#66b3ff', '#99ff99', '#ffcc99', '#c2c2f0']

plt.figure(figsize=(8, 8))
plt.pie(yuzdeler, labels=etiketler, colors=renkler, autopct='%1.1f%%', startangle=90)
plt.title('Programlama Dilleri Dağılımı')
plt.show()

"""#Subplots - Alt Grafikler

Çoklu Grafik Düzenleri (Subplots)


Açıklama: Genellikle verinin farklı yönlerini aynı anda incelemek için tek bir pencerede birden fazla grafik çizmemiz gerekir. Matplotlib'de bu işleme subplot denir.

**`plt.subplots() `ile Izgara Yapı**
`plt.subplots(nrows, ncols)` en yaygın kullanılan yöntemdir. Otomatik olarak bir Figure ve belirtilen sayıda Axes nesnesi döndürür.

Örnek: 2x2 Izgara Yapı
"""

# Tek bir Figure (fig) üzerinde 2 satır ve 2 sütun olmak üzere 4 adet Axes (ax) oluştur
fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(10, 8))
# ax artık bir 2D NumPy dizisidir, bu yüzden indekleme ile erişilir: ax[satır, sütun]

# Veri
x = np.linspace(0, 5, 50)
y1 = x
y2 = x**2
y3 = np.sqrt(x)
y4 = x**3

# Sol Üst (0, 0)
ax[0, 0].plot(x, y1, 'r')
ax[0, 0].set_title('Doğrusal (y=x)')

# Sağ Üst (0, 1)
ax[0, 1].plot(x, y2, 'g')
ax[0, 1].set_title('Karesel (y=x^2)')

# Sol Alt (1, 0)
ax[1, 0].plot(x, y3, 'b')
ax[1, 0].set_title('Karekök (y=sqrt(x))')

# Sağ Alt (1, 1)
ax[1, 1].plot(x, y4, 'purple')
ax[1, 1].set_title('Küpsel (y=x^3)')

# Tüm grafikler için ana bir başlık
fig.suptitle('Farklı Matematiksel Fonksiyonlar', fontsize=16)

# Grafiklerin birbirine binmesini engellemek için boşluk ayarı
fig.tight_layout(pad=3.0)

plt.show()

"""**add_subplot() ile Asimetrik Düzenler**
Bazen simetrik olmayan düzenler gerekebilir. Bu durumda, her bir Axes'i tek tek ekleyebiliriz.
"""

fig = plt.figure(figsize=(9, 6))

# (satır sayısı, sütun sayısı, konum)
# Grafik 1: Sol tarafta tam yer kaplasın (2 satır, 1 sütunun 1.si)
ax1 = fig.add_subplot(2, 2, 1) # Sol Üst
ax1.plot(x, y1, label='Grafik 1')

# Grafik 2: Sağ Üst
ax2 = fig.add_subplot(2, 2, 2)
ax2.plot(x, y2, label='Grafik 2')

# Grafik 3: Alt tarafta tam yer kaplasın (2 satır, 1 sütunun 2.si)
ax3 = fig.add_subplot(2, 1, 2)
ax3.plot(x, y3, label='Grafik 3')

fig.tight_layout()
plt.show()

# 2x2 alt grafik düzeni
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Veri oluşturma
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = np.tan(x)
y4 = np.exp(x/10)

# 1. grafik
axes[0, 0].plot(x, y1, 'r-')
axes[0, 0].set_title('Sinüs Fonksiyonu')
axes[0, 0].grid(True)

# 2. grafik
axes[0, 1].plot(x, y2, 'b-')
axes[0, 1].set_title('Kosinüs Fonksiyonu')
axes[0, 1].grid(True)

# 3. grafik
axes[1, 0].plot(x, y3, 'g-')
axes[1, 0].set_title('Tanjant Fonksiyonu')
axes[1, 0].grid(True)
axes[1, 0].set_ylim(-5, 5)

# 4. grafik
axes[1, 1].plot(x, y4, 'm-')
axes[1, 1].set_title('Üstel Fonksiyon')
axes[1, 1].grid(True)

plt.tight_layout()
plt.show()

"""#Stil ve Görünüm Özelleştirme

#Stil Şablonları
"""

# Mevcut stilleri görüntüleme
print(plt.style.available)

# Stil uygulama
plt.style.use('seaborn-v0_8')

# Örnek grafik
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)

plt.figure(figsize=(10, 6))
plt.plot(x, y1, label='sin(x)', linewidth=2)
plt.plot(x, y2, label='cos(x)', linewidth=2)
plt.title('Stil Uygulanmış Grafik', fontsize=16)
plt.xlabel('x', fontsize=12)
plt.ylabel('y', fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

"""#Detaylı Özelleştirme"""

# Detaylı özelleştirme örneği
fig, ax = plt.subplots(figsize=(12, 8))

# Veri oluşturma
x = np.linspace(0, 2*np.pi, 100)
y1 = np.sin(x)
y2 = np.cos(x)

# Grafik çizimi
ax.plot(x, y1, label='sin(x)', color='red', linewidth=3, linestyle='-', marker='o', markersize=4)
ax.plot(x, y2, label='cos(x)', color='blue', linewidth=3, linestyle='--', marker='s', markersize=4)

# Eksen özelleştirme
ax.set_xlabel('X Değerleri', fontsize=14, fontweight='bold')
ax.set_ylabel('Y Değerleri', fontsize=14, fontweight='bold')
ax.set_title('Trigonometrik Fonksiyonlar', fontsize=16, fontweight='bold')

# Eksen limitleri
ax.set_xlim(0, 2*np.pi)
ax.set_ylim(-1.5, 1.5)

# Kılavuz çizgileri
ax.grid(True, which='both', alpha=0.3, linestyle='-', linewidth=0.5)

# Eksen çizgileri
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_linewidth(2)
ax.spines['bottom'].set_linewidth(2)

# Lejant
ax.legend(loc='upper right', frameon=True, fancybox=True, shadow=True, fontsize=12)

# Özel işaretler
ax.axhline(y=0, color='k', linestyle='-', alpha=0.3)
ax.axvline(x=np.pi, color='gray', linestyle=':', alpha=0.5, label='x=π')

plt.tight_layout()
plt.show()

"""#3d grafikler"""

from mpl_toolkits.mplot3d import Axes3D

# 3D yüzey grafiği
fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection='3d')

# Veri oluşturma
x = np.linspace(-5, 5, 50)
y = np.linspace(-5, 5, 50)
X, Y = np.meshgrid(x, y)
Z = np.sin(np.sqrt(X**2 + Y**2))

# 3D yüzey çizimi
surface = ax.plot_surface(X, Y, Z, cmap='viridis', alpha=0.9)

# Eksen etiketleri
ax.set_xlabel('X Ekseni')
ax.set_ylabel('Y Ekseni')
ax.set_zlabel('Z Ekseni')
ax.set_title('3D Yüzey Grafiği')

# Renk barı
fig.colorbar(surface, ax=ax, shrink=0.5, aspect=5)

plt.show()

"""#Pandas İle Entegrasyon"""

# Pandas DataFrame ile kullanım
df = pd.DataFrame({
    'Aylar': ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran'],
    'Satışlar': [150, 200, 180, 300, 250, 400],
    'Giderler': [100, 120, 110, 150, 130, 180],
    'Kar': [50, 80, 70, 150, 120, 220]
})

# DataFrame'den direkt grafik oluşturma
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Çubuk grafik
df.plot(x='Aylar', y=['Satışlar', 'Giderler'], kind='bar', ax=ax1)
ax1.set_title('Aylık Satışlar ve Giderler')
ax1.set_ylabel('Miktar')

# Çizgi grafik
df.plot(x='Aylar', y='Kar', kind='line', marker='o', ax=ax2, color='green')
ax2.set_title('Aylık Kar')
ax2.set_ylabel('Kar Miktarı')

plt.tight_layout()
plt.show()

"""#İleri Seviye Özellikler

#Animasyonlar
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# Şekil ve eksen oluştur
fig, ax = plt.subplots(figsize=(8, 6))

# X verisi (0 ile 4π arası 100 nokta)
x = np.linspace(0, 4 * np.pi, 100)

# Başlangıç sinüs eğrisi
line, = ax.plot(x, np.sin(x))

# Y eksen aralığını sabitle (aksi halde titrer)
ax.set_ylim(-1.5, 1.5)

# Her frame'de çağrılacak fonksiyon
def animate(frame):
    line.set_ydata(np.sin(x + frame / 10))  # fazı kaydır
    return line,

# Animasyon oluştur
ani = FuncAnimation(fig, animate, frames=100, interval=50, blit=True)

# Göster
plt.show()

ani.save('sinus_animasyonu.gif', writer='pillow', fps=20)

from IPython.display import Image
Image(open('sinus_animasyonu.gif','rb').read())

"""#özel grafikler"""

# Box plot ve Violin plot
np.random.seed(42)
data1 = np.random.normal(0, 1, 100)
data2 = np.random.normal(1, 1.5, 100)
data3 = np.random.normal(-1, 0.5, 100)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

# Box plot
ax1.boxplot([data1, data2, data3])
ax1.set_title('Box Plot')
ax1.set_xticklabels(['Grup 1', 'Grup 2', 'Grup 3'])

# Violin plot
ax2.violinplot([data1, data2, data3])
ax2.set_title('Violin Plot')
ax2.set_xticks([1, 2, 3])
ax2.set_xticklabels(['Grup 1', 'Grup 2', 'Grup 3'])

plt.tight_layout()
plt.show()

"""#kaydet ve çıktı alma"""

# Grafikleri kaydetme
x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(10, 6))
plt.plot(x, y)
plt.title('Kaydedilecek Grafik')

# Farklı formatlarda kaydetme
plt.savefig('grafik.png', dpi=300, bbox_inches='tight')  # PNG formatında
plt.savefig('grafik.pdf', bbox_inches='tight')           # PDF formatında
plt.savefig('grafik.svg', bbox_inches='tight')           # SVG formatında

plt.show()

"""# **Özet**
Matplotlib, Python'da veri görselleştirme için güçlü ve esnek bir kütüphanedir. Temel özellikleri:

Kolay kullanım ve MATLAB benzeri syntax

Geniş grafik yelpazesi (çizgi, dağılım, çubuk, histogram, pasta, vb.)

Yüksek özelleştirilebilirlik

3D grafik desteği

Pandas ve NumPy ile entegrasyon

Profesyonel kalitede çıktı

# **1. Seaborn Nedir ?**

**Seaborn**, **Matplotlib** tabanlı, istatistiksel veri görselleştirme için geliştirilmiş üst düzey bir Python kütüphanesidir. Michael Waskom tarafından geliştirilmiştir ve özellikle istatistiksel analizlerde kullanılan grafikler için optimize edilmiştir.

* **Temel Özellikleri:**  

1. Matplotlib'e göre daha az kodla daha güzel grafikler

2. Pandas DataFrame'leri ile doğrudan entegrasyon

3. Otomatik istatistiksel hesaplamalar

4. Gelişmiş renk paletleri

5. Çok değişkenli veri görselleştirme desteği

# **2. Neden Seaborn Kullanılır ?**

* **Avantajları:**
1. Görsel Kalite: Varsayılan olarak estetik açıdan hoş grafikler

2. Kod Basitliği: Daha az kodla daha çok iş

3. İstatistiksel Odaklı: İstatistiksel analizler için özel fonksiyonlar

3. Renk Paletleri: Gelişmiş ve anlamlı renk şemaları

4. Pandas Entegrasyonu: DataFrame'lerle doğrudan çalışma

# **Matplotlib'den Farkları:**
* Daha üst seviye API

* Otomatik istatistiksel hesaplamalar

* Daha modern ve temiz görünüm

* Dataset odaklı çalışma

# **3. Temel Kurulum ve Import**


```
# Kurulum
# pip install seaborn

# Import işlemleri
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Varsayılan stil ayarı
sns.set_theme()  # Temalar: darkgrid, whitegrid, dark, white, ticks
```
"""

# Kurulum
# pip install seaborn

# Import işlemleri
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Varsayılan stil ayarı
sns.set_theme()  # Temalar: darkgrid, whitegrid, dark, white, ticks

"""# **Temel İçe Aktarma ve Veri Yükleme**"""

import matplotlib.pyplot as plt # Seaborn, Matplotlib'i kullandığı için yine gerekli
import seaborn as sns          # Seaborn'u standart kısaltmasıyla içe aktar
import pandas as pd            # Veri işleme için

# Seaborn'un yerleşik (örnek) veri setlerinden birini yükleyelim
# Bu veri seti, veri biliminde çok sık kullanılır.
df_tips = sns.load_dataset('tips')
print("Veri Setinin İlk 5 Satırı:")
print(df_tips.head())

"""# **4. Temel Grafik Türleri ve Kullanımı**

# **4.1 Line Plot - Çizgi Grafik**
"""

# Örnek veri oluşturma
np.random.seed(42)
time = pd.date_range('2023-01-01', periods=100, freq='D')
values = np.cumsum(np.random.randn(100)) + 100

df = pd.DataFrame({'Tarih': time, 'Değer': values})

# Seaborn line plot
plt.figure(figsize=(12, 6))
sns.lineplot(data=df, x='Tarih', y='Değer',
             marker='o', markersize=4, linewidth=2.5)
plt.title('Zaman Serisi Verisi', fontsize=14, fontweight='bold')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# **4.2 Scatter Plot (Dağılım Grafiği)**"""

# Built-in dataset kullanımı
tips = sns.load_dataset("tips")

plt.figure(figsize=(10, 8))
scatter = sns.scatterplot(data=tips, x='total_bill', y='tip',
                         hue='size', size='size',
                         palette='viridis', alpha=0.7)
plt.title('Bahşiş vs Toplam Hesap', fontsize=14)
plt.xlabel('Toplam Hesap ($)')
plt.ylabel('Bahşiş ($)')
plt.legend(title='Kişi Sayısı', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""# **4.3 Bar Plot (Çubuk Grafik)**

Seaborn'daki barplot, Matplotlib'deki bar'dan farklı olarak, her kategorideki değerlerin ortalama değerini (ve varsayılan olarak hata çubuğunu) gösterir.

"""

fig, ax = plt.subplots(figsize=(8, 5))

# Day (gün) kategorisine göre total_bill'in ortalaması
# estimator=np.mean (varsayılan: ortalama hesaplar)
sns.barplot(data=df_tips,
            x='day',
            y='total_bill',
            hue='sex', # Erkek ve Kadın olarak karşılaştırma
            palette='Pastel1',
            ax=ax)

ax.set_title('Cinsiyete Göre Günlük Ortalama Hesap Miktarı')
ax.set_xlabel('Haftanın Günü')
ax.set_ylabel('Ortalama Hesap ($)')

plt.show()

# Gruplandırılmış çubuk grafik
plt.figure(figsize=(10, 6))
bar_plot = sns.barplot(data=tips, x='day', y='total_bill', hue='sex',
                       palette=['lightblue', 'pink'], ci=None,
                       capsize=0.05, errwidth=1.5)
plt.title('Günlere Göre Ortalama Hesap (Cinsiyete Göre)', fontsize=14)
plt.xlabel('Gün')
plt.ylabel('Ortalama Toplam Hesap ($)')
plt.legend(title='Cinsiyet')
plt.show()

"""# **4.4 Histogram ve KDE (Kernel Density Estimation)**

Seaborn'daki histplot (Matplotlib'deki hist benzeri) ve kdeplot (Kernel Yoğunluk Tahmini) dağılımın şeklini gösterir.  

Kategorik ve sürekli değişkenlerin dağılımını özetleyen, istatistiksel olarak zengin grafikler. Bu grafikler, bir değişkenin dörtte birlik aralıklarını, medyanını ve aykırı değerlerini gösterir.
"""

# total_bill (toplam hesap) değişkeninin dağılımını inceleyelim
fig, ax = plt.subplots(figsize=(8, 4))

# Histogram (Seaborn stilinde, Matplotlib'e göre daha estetik)
sns.histplot(data=df_tips, # Veri kaynağı (Pandas DataFrame)
             x='total_bill', # X ekseninde kullanılacak sütun
             bins=15,
             kde=True, # Yoğunluk tahmini çizgisini ekle
             color='darkorange',
             ax=ax)

ax.set_title('Toplam Hesap Dağılımı (Histplot + KDE)')
plt.show()

# Sadece Yoğunluk Grafiği (KDE)
fig, ax = plt.subplots(figsize=(8, 4))
sns.kdeplot(data=df_tips, x='total_bill', fill=True, color='teal', ax=ax)
ax.set_title('Toplam Hesap Yoğunluk Tahmini (KDE Plot)')
plt.show()

# Histogram ve KDE
plt.figure(figsize=(12, 5))

# Alt grafikler
plt.subplot(1, 2, 1)
sns.histplot(data=tips, x='total_bill', bins=20, kde=True, color='skyblue')
plt.title('Histogram with KDE')

plt.subplot(1, 2, 2)
sns.kdeplot(data=tips, x='total_bill', hue='time', fill=True,
            palette='pastel', alpha=0.6)
plt.title('KDE Plot (Zamana Göre)')

plt.tight_layout()
plt.show()

"""# **4.5 Box Plot ve Violin Plot**

Box Plot:  Verinin medyan, çeyrekler ve aykırı değerler üzerinden özetlenmesi.
`sns.boxplot(x=kategori, y=değer) `

Violin Plot : Kutu grafiğiyle aynı özet bilgileri verir, ancak yanlarda dağılımın şeklini (yoğunluk tahmini) gösterir. Box Plot'tan daha fazla bilgi sunar.

Komut: `sns.violinplot(x=kategori, y=değer)`
"""

# Veri: time (Öğle yemeği mi, Akşam yemeği mi?) kategorisine göre total_bill dağılımı
fig, ax = plt.subplots(figsize=(8, 5))

sns.boxplot(data=df_tips,
            x='time',      # Kategorik değişken (X ekseni)
            y='total_bill',# Sayısal değişken (Y ekseni)
            palette='Set2', # Renk paleti
            ax=ax)

ax.set_title('Öğle ve Akşam Yemeği Hesaplarının Karşılaştırması (Box Plot)')
ax.set_xlabel('Öğün Zamanı')
ax.set_ylabel('Toplam Hesap ($)')

plt.show()

#Violin

fig, ax = plt.subplots(figsize=(8, 5))

sns.violinplot(data=df_tips,
               x='day', # Haftanın günleri
               y='tip', # Bahşiş miktarı
               palette='viridis',
               ax=ax)

ax.set_title('Haftanın Günlerine Göre Bahşiş Dağılımı (Violin Plot)')
ax.set_xlabel('Haftanın Günü')
ax.set_ylabel('Bahşiş Miktarı ($)')

plt.show()

# Box plot ve violin plot karşılaştırması
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.boxplot(data=tips, x='day', y='total_bill', hue='smoker',
            palette='Set2')
plt.title('Box Plot')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

plt.subplot(1, 2, 2)
sns.violinplot(data=tips, x='day', y='total_bill', hue='smoker',
               split=True, palette='Set2', inner='quartile')
plt.title('Violin Plot')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

"""# **4.6 Nokta Grafiği (Point Plot)**
Çubuk grafiklerine benzer, ancak ortalamaları dikey çizgiler üzerinde noktalarla gösterir. Birden fazla kategoriyi tek bir eksende karşılaştırmak için faydalıdır.

# **5. İstatistiksel Grafikler**

# **5.1 Pair Plot (Çiftler Grafiği)**
"""

# Pair plot - çok değişkenli analiz
iris = sns.load_dataset("iris")

pair_grid = sns.pairplot(iris, hue='species', palette='husl',
                        diag_kind='kde', markers=['o', 's', 'D'])
pair_grid.fig.suptitle('Iris Dataset - Pair Plot', y=1.02, fontsize=16)
plt.show()

"""# **5.2 Heatmap (Isı Haritası)**

İkiden fazla sayısal değişken arasındaki korelasyonu tek bir matriste görselleştirmek için kullanılır.
"""

# Sadece sayısal sütunları seçip korelasyon matrisi hesaplama
df_corr = df_tips[['total_bill', 'tip', 'size']].corr()

fig, ax = plt.subplots(figsize=(6, 5))

# Isı Haritası (Heatmap) çizimi
sns.heatmap(df_corr,
            annot=True,     # Kutucukların içine korelasyon değerlerini yaz
            cmap='viridis', # Renk paleti
            fmt=".2f",      # Sayı formatı (2 ondalık)
            linewidths=.5,  # Çizgilerin kalınlığı
            cbar=True,      # Renk çubuğunu göster
            ax=ax)

ax.set_title('Sayısal Değişkenler Arasındaki Korelasyon Matrisi')
plt.show()

# Korelasyon heatmap'i
plt.figure(figsize=(10, 8))

# Korelasyon matrisini hesapla
corr_matrix = iris.select_dtypes(include=[np.number]).corr()

# Heatmap oluştur
heatmap = sns.heatmap(corr_matrix, annot=True, cmap='coolwarm',
                      center=0, square=True, fmt='.2f',
                      cbar_kws={'shrink': 0.8})
plt.title('Iris Dataset - Korelasyon Matrisi', fontsize=14)
plt.tight_layout()
plt.show()

"""# **5.3 Joint Plot (Birleşik Grafik)**"""

# Joint plot - dağılım ve histogram birleşimi
joint = sns.jointplot(data=iris, x='sepal_length', y='sepal_width',
                     hue='species', palette='dark', alpha=0.7,
                     kind='scatter', height=8)
joint.fig.suptitle('Sepal Length vs Sepal Width', y=1.02, fontsize=14)
plt.tight_layout()
plt.show()

"""# **6. Kategoriye Göre Grafikler**
# **6.1 Cat Plot (Kategorik Grafik)**
"""

# Catplot - esnek kategorik grafikler
plt.figure(figsize=(12, 6))
cat_plot = sns.catplot(data=tips, x='day', y='total_bill', hue='sex',
                       kind='box', col='time', palette='pastel',
                       height=6, aspect=1.2)
cat_plot.fig.suptitle('Hesap Dağılımı (Gün ve Zamana Göre)', y=1.02)
plt.show()

"""# **6.2 Count Plot (Sayım Grafiği)**

Bu, sadece kategorik değişkenlerin frekansını (sayısını) göstermek için kullanılır. Y eksenini otomatik olarak sayar.
"""

fig, ax = plt.subplots(figsize=(8, 5))

# Day (gün) kategorisindeki gözlem sayısını sayar
sns.countplot(data=df_tips,
              x='day',
              order=['Thur', 'Fri', 'Sat', 'Sun'], # Gün sırasını belirleme
              color='lightblue',
              edgecolor='black',
              ax=ax)

ax.set_title('Veri Setindeki Günlük Gözlem Sayıları')
ax.set_xlabel('Haftanın Günü')
ax.set_ylabel('Gözlem Sayısı (Frekans)')

plt.show()

# Count plot - kategorik değişken frekansları
plt.figure(figsize=(10, 6))
count_plot = sns.countplot(data=tips, x='day', hue='sex',
                          palette='Set3', saturation=0.8)
plt.title('Günlere Göre Ziyaret Sayısı (Cinsiyete Göre)', fontsize=14)
plt.xlabel('Gün')
plt.ylabel('Sayı')

# Değerleri üzerine yazma
for container in count_plot.containers:
    count_plot.bar_label(container, fontsize=10)

plt.show()

"""# **7. Stil ve Görünüm Özelleştirme**
# **7.1 Temalar ve Renk Paletleri**

Matplotlib'deki scatter'dan farklı olarak, Seaborn'un scatterplot'u, verideki ek kategorik değişkenleri (örneğin renk, boyut veya şekil) kullanarak daha fazla boyutu görselleştirmemizi sağlar.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Veri setini tekrar yükleyelim
df_tips = sns.load_dataset('tips')

fig, ax = plt.subplots(figsize=(10, 6))

# total_bill (X) ve tip (Y) arasındaki ilişkiyi çizelim
# hue: Grafik noktalarını 'time' (zaman) kategorisine göre renklendir
# style: Grafik noktalarının şeklini 'smoker' (sigara içen) kategorisine göre ayarla
sns.scatterplot(data=df_tips,
                x='total_bill',
                y='tip',
                hue='time',      # Renk ile 3. değişkeni göster
                style='smoker',  # Şekil ile 4. değişkeni göster
                s=80,            # Nokta boyutu
                ax=ax)

ax.set_title('Toplam Hesap ve Bahşiş İlişkisi (Zaman ve Sigara Durumuna Göre)')
ax.legend(title='Öğün Zamanı', loc='upper left')

plt.show()

# Farklı temaları deneme
themes = ['darkgrid', 'whitegrid', 'dark', 'white', 'ticks']
palettes = ['deep', 'muted', 'pastel', 'bright', 'dark', 'colorblind']

# Renk paleti örnekleri
plt.figure(figsize=(15, 10))

for i, (theme, palette) in enumerate(zip(themes[:3], palettes[:3])):
    sns.set_theme(style=theme)

    plt.subplot(2, 3, i+1)
    sns.scatterplot(data=iris, x='sepal_length', y='sepal_width',
                   hue='species', palette=palette)
    plt.title(f'Theme: {theme}, Palette: {palette}')

sns.set_theme(style='whitegrid')  # Varsayılan temaya dön
plt.tight_layout()
plt.show()

"""# **7.2 Detaylı Özelleştirme**"""

# Detaylı özelleştirme örneği
with sns.axes_style("whitegrid"):
    plt.figure(figsize=(12, 8))

    # Özel renk paleti
    custom_palette = sns.color_palette("husl", 3)

    # Violin plot with swarm plot
    ax = sns.violinplot(data=iris, x='species', y='petal_length',
                       palette=custom_palette, inner=None, alpha=0.7)
    sns.swarmplot(data=iris, x='species', y='petal_length',
                 color='black', alpha=0.8, size=3)

    # Grafik özelleştirme
    ax.set_title('Iris Türlerine Göre Taç Yaprak Uzunluğu Dağılımı',
                fontsize=16, fontweight='bold', pad=20)
    ax.set_xlabel('Iris Türleri', fontsize=12, fontweight='bold')
    ax.set_ylabel('Taç Yaprak Uzunluğu (cm)', fontsize=12, fontweight='bold')

    # Eksen çizgileri
    sns.despine(left=True, bottom=True)

plt.tight_layout()
plt.show()

"""# **7.3 Grafik Stilini Ayarlama**

Seaborn, arka plan, ızgara çizgileri ve kenarlıklar gibi görsel öğeler için hazır stiller sunar.

## 🎨 Seaborn Stil Ayarları

| Stil | Açıklama |
|------|-----------|
| `whitegrid` | Beyaz arka plan ve ızgara çizgileri (**çok popüler**). |
| `darkgrid` | Koyu arka plan ve ızgara çizgileri. |
| `white` | Beyaz arka plan, ızgara yok. |
| `dark` | Koyu arka plan, ızgara yok. |
| `ticks` | Beyaz arka plan ve eksen kenarlarında küçük işaretler. |

"""

import seaborn as sns
import matplotlib.pyplot as plt

# Grafiğin stilini değiştirelim (Örn: beyaz ızgara)
sns.set_style('whitegrid')

# Örnek bir Box Plot çizelim
df_tips = sns.load_dataset('tips')

plt.figure(figsize=(8, 5))
sns.boxplot(data=df_tips, x='day', y='total_bill')
plt.title('Beyaz Izgara Stili ile Box Plot')

# Stili değiştirelim ve başka bir grafik çizelim
sns.set_style('ticks')
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df_tips, x='total_bill', y='tip')
plt.title('Ticks Stili ile Scatter Plot')

plt.show()

# Not: Genellikle ders başında bir stil belirlenir ve tüm ders boyunca aynı stil kullanılır.
sns.set_style('whitegrid') # Standart stile dönelim

"""# **7.4 Renk Paletlerini Kullanma**
Seaborn, yüzlerce renk paleti sunar. Bu paletler, veri türüne (sıralı, kategorik, farklılık gösteren) göre seçilebilir.
"""

# Bazı popüler paletler: 'viridis', 'magma', 'Set1', 'Pastel2', 'rocket'

plt.figure(figsize=(8, 5))

# 'rocket' (koyu tonlardan açığa) sıralı paletini kullanalım
sns.barplot(data=df_tips,
            x='day',
            y='tip',
            palette='rocket')

plt.title("Rocket Paleti ile Bar Plot")
plt.show()

# 'Set2' (kategorik, farklı renkler) paletini kullanalım
plt.figure(figsize=(8, 5))
sns.violinplot(data=df_tips, x='time', y='total_bill', palette='Set2')
plt.title("Set2 Paleti ile Violin Plot")
plt.show()

"""# **8. Regresyon Grafikleri**
# **8.1 Reg Plot (Regresyon Grafiği)**
Bu grafikler, iki değişken arasındaki doğrusal ilişkiyi göstermenin yanı sıra, en uygun regresyon çizgisini ve etrafındaki güven aralığını otomatik olarak ekler.

"""

fig, ax = plt.subplots(figsize=(8, 5))

# total_bill ve tip arasındaki doğrusal ilişkiyi göster
# ci=95: %95 güven aralığını göster (varsayılan)
sns.regplot(data=df_tips,
            x='total_bill',
            y='tip',
            scatter_kws={'color': 'teal', 'alpha': 0.7}, # Nokta ayarları
            line_kws={'color': 'red'},                  # Çizgi ayarları
            ax=ax)

ax.set_title('Regresyon Çizgisi ile Bahşiş Tahmini')
plt.show()

# Regresyon grafikleri
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.regplot(data=tips, x='total_bill', y='tip',
           scatter_kws={'alpha':0.5}, line_kws={'color': 'red'})
plt.title('Basit Doğrusal Regresyon')

plt.subplot(1, 3, 2)
sns.regplot(data=tips, x='total_bill', y='tip',
           lowess=True, scatter_kws={'alpha':0.5})
plt.title('LOWESS Regresyon')

plt.subplot(1, 3, 3)
sns.residplot(data=tips, x='total_bill', y='tip',
             scatter_kws={'alpha':0.5})
plt.title('Artık Grafiği')

plt.tight_layout()
plt.show()

"""# **8.2 LM Plot (Doğrusal Model Grafiği)**"""

# LM plot - gruplara göre regresyon
lm = sns.lmplot(data=tips, x='total_bill', y='tip', hue='smoker',
                col='time', row='sex', palette='Set1',
                height=4, aspect=1.2, ci=95)
lm.fig.suptitle('Bahşiş Regresyon Analizi (Gruplara Göre)', y=1.02)
plt.show()

"""# **9. Çok Değişkenli Analiz**
# **9.1 Facet Grid (Yüzey Izgarası)**
FacetGrid veya yüksek seviyeli karşılıkları (relplot, catplot), büyük bir veri setini bir veya iki kategorik değişkenin değerlerine göre böler ve her bir alt küme için aynı grafiği çeker. Bu, alt gruplar arasındaki farkları hızlıca görmemizi sağlar.
"""

#Örnek: Günlere Göre Farklı Boyutlarda Bahşiş Dağılımı
# sns.catplot, kategorik bir grafik türünü (örneğin boxplot) FacetGrid içine yerleştirir.
sns.catplot(data=df_tips,
            x='time',        # X ekseni: Öğün Zamanı
            y='tip',         # Y ekseni: Bahşiş Miktarı
            kind='box',      # Çizilecek grafik türü (boxplot, violin, bar vb.)
            col='day',       # Sütunları 'day' (gün) kategorisine göre böl
            col_wrap=2,      # Sütun sayısını en fazla 2 ile sınırla
            height=4,        # Her alt grafiğin yüksekliği
            aspect=1.2,      # Her alt grafiğin en/boy oranı
            palette='muted')

plt.suptitle('Öğün Zamanı ve Bahşiş Dağılımı (Günlere Göre Ayrı Ayrı)', y=1.02)
plt.show()

# FacetGrid - gelişmiş çoklu grafikler
g = sns.FacetGrid(tips, col='time', row='smoker', hue='sex',
                  palette='Set2', height=4, aspect=1.2)
g.map(sns.scatterplot, 'total_bill', 'tip', alpha=0.7)
g.add_legend()
g.fig.suptitle('Çok Boyutlu Veri Analizi', y=1.02, fontsize=16)
plt.show()

"""# **9.2 Cluster Map (Kümeleme Haritası)**"""

# Cluster map - hiyerarşik kümeleme
plt.figure(figsize=(12, 8))

# Sayısal sütunları seç
numeric_iris = iris.select_dtypes(include=[np.number])

# Cluster map oluştur
cluster_grid = sns.clustermap(numeric_iris,
                             standard_scale=1,
                             cmap='viridis',
                             figsize=(10, 8))
cluster_grid.fig.suptitle('Iris Dataset - Kümeleme Haritası', y=1.02)
plt.show()

"""# **10. Gelişmiş Özellikler**
# **10.1 Distribution Plot (Dağılım Grafiği)**
"""

# Gelişmiş dağılım grafiği
plt.figure(figsize=(12, 6))

# Distribution plot
sns.displot(data=tips, x='total_bill', hue='day', kind='kde',
           palette='tab10', height=6, aspect=1.5)
plt.title('Günlere Göre Hesap Dağılımı')
plt.show()

"""# **10.2 Ridge Plot (Sırt Grafiği)**"""

# Ridge plot (gerekli kütüphaneler)
# pip install joypy

import joypy

# Ridge plot benzeri görselleştirme
plt.figure(figsize=(12, 8))

# Violin plot ile ridge plot efekti
sns.violinplot(data=iris, y='species', x='sepal_length',
              palette='light:g', inner=None, saturation=0.5)
sns.stripplot(data=iris, y='species', x='sepal_length',
             size=3, color='black', alpha=0.3)
plt.title('Ridge Plot Benzeri Görselleştirme', fontsize=14)
plt.tight_layout()
plt.show()

"""# **11. Pandas ile Derin Entegrasyon**"""

# Pandas DataFrame ile komple analiz
# Veri seti yükleme
mpg = sns.load_dataset("mpg")

# Komple analiz
g = sns.PairGrid(mpg.select_dtypes(include=[np.number]).iloc[:, :4])
g.map_upper(sns.scatterplot, alpha=0.6)
g.map_lower(sns.kdeplot, fill=True)
g.map_diag(sns.histplot, kde=True)
g.fig.suptitle('MPG Dataset - Çok Değişkenli Analiz', y=1.02, fontsize=16)
plt.show()

"""# **12. Kaydetme ve Export**"""

# Grafik kaydetme
plt.figure(figsize=(10, 6))
final_plot = sns.boxplot(data=mpg, x='origin', y='mpg', palette='Set3')
plt.title('Menşei Ülkeye Göre MPG Dağılımı', fontsize=14)

# Yüksek kalitede kaydetme
plt.savefig('seaborn_grafik.png', dpi=300, bbox_inches='tight',
            facecolor='white', edgecolor='none')
plt.savefig('seaborn_grafik.pdf', bbox_inches='tight')

plt.show()

"""## **Özet ve En İyi Uygulamalar**
**Seaborn'un Güçlü Yönleri:**  

* Hızlı prototipleme için ideal

* İstatistiksel görselleştirme için optimize

* Güzel varsayılan ayarlar

* Pandas ile mükemmel uyum

* Çok değişkenli analiz desteği  


**İpuçları:**  

* sns.set_theme() ile temayı başta ayarla

* Built-in dataset'leri kullanarak hızlı başla

* hue parametresi ile gruplandırma yap

* pairplot ile hızlı keşifsel analiz

* catplot ile esnek kategorik grafikler

**Ne Zaman Seaborn Kullanılır?**  

* Hızlı ve güzel grafikler için

* İstatistiksel analizlerde

* Pandas DataFrame'lerle çalışırken

* Gruplandırılmış verilerde

* Keşifsel veri analizinde  


Seaborn, özellikle istatistiksel analiz ve hızlı veri keşfi için Matplotlib'den daha pratik bir çözüm sunar. İkisini birlikte kullanarak en iyi sonuçları alabilirsiniz.

Mini Proje

Mini Proje Akışı:

1. Veri Yükleme: sns.load_dataset('iris') (İris çiçekleri veri seti)

2. Korelasyon: Hangi değişkenler en güçlü ilişkiye sahip? (Heatmap)

3. Dağılım: sepal_length değişkeninin dağılımı nasıl? (Histplot)

4. İlişki: petal_length ve petal_width arasındaki ilişkiyi türlere göre renklendirerek göster. (Scatterplot)
"""

# Yeni veri seti
df_iris = sns.load_dataset('iris')
print("\n--- Iris Veri Seti ---")
print(df_iris.head())

# İlişki görselleştirme (4. Adım)
plt.figure(figsize=(8, 6))
sns.scatterplot(data=df_iris,
                x='petal_length',
                y='petal_width',
                hue='species', # Tür (species) kategorisine göre renklendir
                s=100,
                alpha=0.8)

plt.title('Taç Yaprağı Uzunluğu ve Genişliği İlişkisi (Türlere Göre)')
plt.legend(title='Çiçek Türü')
plt.show()

"""Ana Çıkarımlar:

Matplotlib: Figure (Tuval) ve Axes (Grafik Alanı) kavramları ile tam kontrol.

Seaborn: Daha az kodla daha estetik grafikler, yerleşik istatistiksel hesaplamalar ve Pandas DataFrame entegrasyonu.

Enstrüman Çantası: plot, scatter, bar, hist, boxplot, violinplot, heatmap, regplot, catplot.
"""